### PR TITLE
Feature/syntax checker

### PR DESCRIPTION
**Pull request by dsvictor94**
Preparing to a new release thats include

- Syntax check (big thanks to @pocket7878 PR #3 )
- Upgrade dependencies

### CODE REVIEW

**Comment by dsvictor94** [comment]
@pocket7878 your review would be highly appreciated :)

**Review by pocket7878 — APPROVED** [review]
LGTM!
Thank you for your refactoring my codes !

**Comment by claudiopedrom** [comment]
Hi @dsvictor94 and @pocket7878, I started using Promela for an academic study and I was curious if this PR is going to be merged?

**Comment by dsvictor94** [comment]
Sorry for the probably too long delay @claudiopedrom, but I am merging now and try to publish a new version

**Comment by claudiopedrom** [comment]
Thanks @dsvictor94 , I really appreciate your work! The extension was very useful for me 👏

**Pull request merged**
